### ISSUE TITLE
hosting

### ISSUE THREAD

**Issue by zowhair** [tnolan8/blog#1]
Is this blog hosted on github?

**Comment by tnolan8** [comment]
Hey it's actually hosted on [Heroku](https://www.heroku.com/), highly recommend it. The actually repo you'll want to look at is [tomnolan-ie](https://github.com/tnolan8/tomnolan-ie). I also recommend checking out [Miguel Grinberg's](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world) tutorial series on creating a blog through Flask, it's mostly entirely what this is based on! Goodluck!

**Comment by zowhair** [comment]
Thanks :)
